import os

import anthropic
from fastapi import APIRouter, HTTPException

from app.models.plan import MonthlyPlanContext, MonthlyPlanResponse, MonthlyPlanSection

router = APIRouter(prefix="/plan", tags=["plan"])

_TOOL = {
    "name": "save_monthly_plan",
    "description": "Save the structured monthly financial plan.",
    "input_schema": {
        "type": "object",
        "properties": {
            "surplus": {"type": "number", "description": "Monthly surplus = income - expenses - SIPs"},
            "sections": {
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {"type": "string"},
                        "amount": {"type": "number"},
                        "narrative": {"type": "string", "description": "1-2 sentence insight. Use only figures from the data."},
                    },
                    "required": ["title", "narrative"],
                },
            },
            "overall_narrative": {"type": "string", "description": "3-4 sentence overall summary. Use only figures from the data."},
        },
        "required": ["surplus", "sections", "overall_narrative"],
    },
}

_SYSTEM = """You are a personal financial advisor for Indian retail investors.
Generate a structured monthly financial plan based on the data provided.
Rules:
- Use ONLY figures present in the data. Do NOT invent any numbers.
- Be specific and actionable. Avoid generic advice.
- Write in plain English for a non-expert audience.
- Call save_monthly_plan exactly once with the complete plan."""


def _build_prompt(ctx: MonthlyPlanContext) -> str:
    fmt = lambda n: f"₹{n:,.0f}"  # noqa: E731
    surplus = ctx.total_income - ctx.total_expenses - ctx.total_sip
    lines = [
        f"Monthly income: {fmt(ctx.total_income)}",
        f"Monthly expenses: {fmt(ctx.total_expenses)}",
        f"Monthly SIP commitments: {fmt(ctx.total_sip)}",
        f"Calculated surplus: {fmt(surplus)}",
        f"Net worth: {fmt(ctx.net_worth)}",
        f"Active goals: {ctx.active_goal_count}",
    ]
    if ctx.top_expense_categories:
        lines.append("Top expense categories:")
        for c in ctx.top_expense_categories[:5]:
            lines.append(f"  - {c.get('category', '')}: {fmt(c.get('amount', 0))}")
    if ctx.goals:
        lines.append("Goals:")
        for g in ctx.goals:
            prob = f", {g.get('probability', 0):.0f}% probability" if g.get("probability") else ""
            lines.append(f"  - {g.get('name', '')}: target {fmt(g.get('target', 0))}{prob}")
    return "\n".join(lines)


@router.post("/generate", response_model=MonthlyPlanResponse)
async def generate_plan(ctx: MonthlyPlanContext) -> MonthlyPlanResponse:
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        raise HTTPException(status_code=503, detail="ANTHROPIC_API_KEY not configured.")

    client = anthropic.Anthropic(api_key=api_key)
    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=1024,
            system=_SYSTEM,
            tools=[_TOOL],  # type: ignore[list-item]
            tool_choice={"type": "any"},
            messages=[{"role": "user", "content": _build_prompt(ctx)}],
        )
    except anthropic.APIError as exc:
        raise HTTPException(status_code=502, detail=f"Anthropic API error: {exc}") from exc

    for block in response.content:
        if block.type == "tool_use" and block.name == "save_monthly_plan":
            inp = block.input
            sections = [
                MonthlyPlanSection(
                    title=s["title"],
                    amount=s.get("amount"),
                    narrative=s["narrative"],
                )
                for s in inp.get("sections", [])
            ]
            return MonthlyPlanResponse(
                surplus=inp["surplus"],
                sections=sections,
                overall_narrative=inp["overall_narrative"],
            )

    raise HTTPException(status_code=500, detail="No plan generated by AI.")
